
-- Добавляем навыки (игнорируем дубликаты)
INSERT INTO skills (name) VALUES
-- Языки программирования
('Python'),
('Java'),
('Go'),
('JavaScript'),
('TypeScript'),
('C++'),
('C#'),
('PHP'),
('Ruby'),
('Kotlin'),
('Swift'),
('Rust'),
-- Фреймворки
('Django'),
('Flask'),
('FastAPI'),
('Spring Boot'),
('Express.js'),
('NestJS'),
('React'),
('Vue.js'),
('Angular'),
('Laravel'),
('Symfony'),
('ASP.NET Core'),
-- Базы данных
('PostgreSQL'),
('MySQL'),
('MongoDB'),
('Redis'),
('SQLite'),
('Cassandra'),
('ClickHouse'),
('Elasticsearch'),
-- DevOps и инфраструктура
('Docker'),
('Kubernetes'),
('GitLab CI/CD'),
('GitHub Actions'),
('Jenkins'),
('Ansible'),
('Terraform'),
('Prometheus'),
('Grafana'),
-- Инструменты и стандарты
('Git'),
('REST API'),
('GraphQL'),
('gRPC'),
('WebSocket'),
('OAuth 2.0'),
('JWT'),
('OpenAPI/Swagger'),
-- Тестирование
('Unit testing'),
('Pytest'),
('JUnit'),
('Postman'),
('Selenium'),
('Mockito'),
('Integration testing'),
('E2E testing'),
-- Дополнительные навыки
('Linux/Unix'),
('Bash scripting'),
('HTML/CSS'),
('JSON/XML'),
('RabbitMQ'),
('Kafka'),
('Nginx'),
('Apache'),
('System Design'),
('Microservices'),
('SOLID'),
('Design Patterns'),
('Agile/Scrum'),
('Jira'),
('Confluence'),
('Figma')
ON CONFLICT (name) DO NOTHING;

