run:
  timeout: 5m
  test: true
  
linters:
  enable:
    - errcheck      # проверка ошибок
    - govet         # подозрительные конструкции
    - staticcheck   # мощный статический анализ
    - gosec         # безопасность
    - revive        # замена golint
    - gofmt         # форматирование
    - goimports     # сортировка импортов
    - dupl          # дублирующийся код
    - gocyclo       # сложность функций
    - godox         # TODO/FIXME комментарии

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  gocyclo:
    min-complexity: 10
